In [1]:
import numpy as np

In [2]:
marks = np.array([78, 92, 36, 64, 89])
marks

array([78, 92, 36, 64, 89])

In [3]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
horsepower_arr

array([130, 165, 150, 150, 140])

In [4]:
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from car_attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr
# type(car_attributes_arr)

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [5]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#mean horsepower
print("Mean horsepower = ",np.mean(horsepower_arr))

Mean horsepower =  147.0


In [6]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#median horsepower
print("Median horsepower = ",np.median(horsepower_arr))

Median horsepower =  150.0


In [7]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))

Minimum horsepower:  130
Maximum horsepower:  165


In [8]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
print("Index of Minimum horsepower: ", np.argmin(horsepower_arr))
print("Index of Maximum horsepower: ", np.argmax(horsepower_arr))

Index of Minimum horsepower:  0
Index of Maximum horsepower:  1


In [9]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x) # gives the indices 
# With the indices , we can find those values 
horsepower_arr[x]

(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#creating filter array
filter_arr = horsepower_arr > 135
newarr = horsepower_arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr))
print('original array after sorting: ', horsepower_arr)


#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
horsepower_arr.sort()
print('original array after sorting: ', horsepower_arr)

In [ ]:
import numpy as np
# Array 1
array1=np.array([5, 10, 15, 10])
# Array 2
array2=np.array([5])
array3= array1 * array2 
array3

In [ ]:
#Students marks in 4 subjects
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
print(students_marks)
extra_marks = np.array([5,10])
# students_marks = np.add(students_marks, extra_marks)
students_marks += extra_marks
print(students_marks)

In [ ]:
#Importing path and skimage i/o library 
import os.path
from skimage.io import imread
from skimage import data_dir
#reading the astronaut image
img = imread(os.path.join(data_dir, 'astronaut.png'))

In [ ]:
print(os.path.join(data_dir, 'astronaut.png'))

In [ ]:
#Using matplotlib.pyplot to visualize the image 
import matplotlib.pyplot as plt
plt.imshow(img)

In [ ]:
print(img)

In [ ]:
img.shape

In [ ]:
#Slicing out the rocket 
img_slice = img.copy()
img_slice = img_slice[0:300,360:480]
plt.figure()
plt.imshow(img_slice)

In [ ]:
img[0:300,360:480,:] = 0
plt.imshow(img)

In [ ]:
img_slice[np.greater_equal(img_slice[:,:,0],100) & np.less_equal(img_slice[:,:,0],150)] = 0
plt.figure()
plt.imshow(img_slice)

In [ ]:
img[0:300,360:480,:] = img_slice
plt.imshow(img)

In [ ]:
np.ones([2,3,4])

In [ ]:
#generating 5 random numbers from a uniform distribution
np.random.rand(5)

In [ ]:
#returns a single random value from the array
x = np.random.choice([9, 3, 7, 5])
print(x)

In [ ]:
x = np.random.choice([9, 3, 7, 5], size=(3, 5))   # sampling to create an nd-array 
print(x)
print(type(x))

In [ ]:
steps = np.array([[1, 6012], [2, 7079], [3, 6886], [4, 7230], [5, 4598], [6, 5564], [7, 6971], [8, 7763], [9, 8032], [10, 9569]])
steps

In [ ]:
steps += [0, 2000]
steps

In [ ]:
filtered = steps[steps > 9000]
np.sort(filtered)